spring:
  application:
    name: tasks
  datasource:
    username: tasks-db
    password: admin
    url: jdbc:postgresql://localhost:5432/tasks

camunda:
  bpm:
    deployment:
      path: bpmn
      changes-only: true
